site_name: InfoSec & Dev by Isaías
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - content.code.copy
    - search.highlight
    - navigation.instant
repo_url: https://github.com/godack1905
repo_name: GitHub
extra:
    social:
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/isa%C3%ADas-vela-sotil-b436431a4/

nav:
  - Home: index.md
  - Writeups:
      - First Hacking: writeups/FirstHacking.md
      - Injection: writeups/Injection.md
      - Trust: writeups/Trust.md
      - Obsession: writeups/Obsession.md
  - Notes:
      - Most common vulnerabilities: notes/VulnerabilityWeb.md
      - Pentesting tools: notes/Tools.md
